"""atualizar tabela transacoes

Revision ID: d044c1e5d1ac
Revises: 91e997ee28a1
Create Date: 2026-08-31 12:15:24.542795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd044c1e5d1ac'
down_revision: Union[str, Sequence[str], None] = '91e997ee28a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Refresh Tokens',
    sa.Column('id_refresh', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('revogado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_refresh')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Refresh Tokens')
    # ### end Alembic commands ###
